export default (app) => {
  app.post(
    `/tenant/:tenantId/config-table`,
    require('./configTableCreate').default,
  );
  app.put(
    `/tenant/:tenantId/config-table/:id`,
    require('./configTableUpdate').default,
  );
  app.post(
    `/tenant/:tenantId/config-table/import`,
    require('./configTableImport').default,
  );
  app.delete(
    `/tenant/:tenantId/config-table`,
    require('./configTableDestroy').default,
  );
  app.get(
    `/tenant/:tenantId/config-table/autocomplete`,
    require('./configTableAutocomplete').default,
  );
  app.get(
    `/tenant/:tenantId/config-table`,
    require('./configTableList').default,
  );
  app.get(
    `/tenant/:tenantId/config-table/:id`,
    require('./configTableFind').default,
  );
};
