export default (app) => {
  app.post(
    `/tenant/:tenantId/prodtype`,
    require('./prodtypeCreate').default,
  );
  app.put(
    `/tenant/:tenantId/prodtype/:id`,
    require('./prodtypeUpdate').default,
  );
  app.post(
    `/tenant/:tenantId/prodtype/import`,
    require('./prodtypeImport').default,
  );
  app.delete(
    `/tenant/:tenantId/prodtype`,
    require('./prodtypeDestroy').default,
  );
  app.get(
    `/tenant/:tenantId/prodtype/autocomplete`,
    require('./prodtypeAutocomplete').default,
  );
  app.get(
    `/tenant/:tenantId/prodtype`,
    require('./prodtypeList').default,
  );
  app.get(
    `/tenant/:tenantId/prodtype/:id`,
    require('./prodtypeFind').default,
  );
};
