export default (app) => {
  app.post(
    `/tenant/:tenantId/family`,
    require('./familyCreate').default,
  );
  app.put(
    `/tenant/:tenantId/family/:id`,
    require('./familyUpdate').default,
  );
  app.post(
    `/tenant/:tenantId/family/import`,
    require('./familyImport').default,
  );
  app.delete(
    `/tenant/:tenantId/family`,
    require('./familyDestroy').default,
  );
  app.get(
    `/tenant/:tenantId/family/autocomplete`,
    require('./familyAutocomplete').default,
  );
  app.get(
    `/tenant/:tenantId/family`,
    require('./familyList').default,
  );
  app.get(
    `/tenant/:tenantId/family/:id`,
    require('./familyFind').default,
  );
};
