export default (app) => {
  app.post(
    `/tenant/:tenantId/p-r-o-d-u-c-tline`,
    require('./pRODUCTlineCreate').default,
  );
  app.put(
    `/tenant/:tenantId/p-r-o-d-u-c-tline/:id`,
    require('./pRODUCTlineUpdate').default,
  );
  app.post(
    `/tenant/:tenantId/p-r-o-d-u-c-tline/import`,
    require('./pRODUCTlineImport').default,
  );
  app.delete(
    `/tenant/:tenantId/p-r-o-d-u-c-tline`,
    require('./pRODUCTlineDestroy').default,
  );
  app.get(
    `/tenant/:tenantId/p-r-o-d-u-c-tline/autocomplete`,
    require('./pRODUCTlineAutocomplete').default,
  );
  app.get(
    `/tenant/:tenantId/p-r-o-d-u-c-tline`,
    require('./pRODUCTlineList').default,
  );
  app.get(
    `/tenant/:tenantId/p-r-o-d-u-c-tline/:id`,
    require('./pRODUCTlineFind').default,
  );
};
