export default (app) => {
  app.post(
    `/tenant/:tenantId/config`,
    require('./configCreate').default,
  );
  app.put(
    `/tenant/:tenantId/config/:id`,
    require('./configUpdate').default,
  );
  app.post(
    `/tenant/:tenantId/config/import`,
    require('./configImport').default,
  );
  app.delete(
    `/tenant/:tenantId/config`,
    require('./configDestroy').default,
  );
  app.get(
    `/tenant/:tenantId/config/autocomplete`,
    require('./configAutocomplete').default,
  );
  app.get(
    `/tenant/:tenantId/config`,
    require('./configList').default,
  );
  app.get(
    `/tenant/:tenantId/config/:id`,
    require('./configFind').default,
  );
};
